# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('attack', models.IntegerField(blank=True, default=1, null=True)),
                ('defence', models.IntegerField(blank=True, default=0, null=True)),
                ('health', models.IntegerField(blank=True, default=1, null=True)),
                ('faction', models.CharField(blank=True, choices=[('N', 'Neutral'), ('P', 'Protoss'), ('Z', 'Zerg'), ('T', 'Terran')], default='N', max_length=1, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
