# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('attack', models.IntegerField(blank=True, default=1, null=True)),
                ('defence', models.IntegerField(blank=True, default=1, null=True)),
                ('health', models.IntegerField(blank=True, default=1, null=True)),
                ('tier', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, null=True)),
                ('faction', models.CharField(blank=True, choices=[('N', 'Neutral'), ('P', 'Protoss'), ('Z', 'Zerg'), ('T', 'Terran')], default='N', max_length=1, null=True)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-attack',),
            },
        ),
    ]
