# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('-attack',)},
        ),
        migrations.AddField(
            model_name='unit',
            name='tier',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='defence',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
