# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8000, host: 8001
  config.vm.network "forwarded_port", guest: 80, host: 81
  config.vm.synced_folder "../.", "/playground/"

  config.vm.provider :virtualbox do |vm|
    vm.name = "docker-playground"
    vm.memory = 3072
  end

  config.vm.provision "shell", path: "provision.sh"

  # EnableSendfile Off
  # sendfile off;

end
