# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_contentediter_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
