const schema = {
  // init
  requester_name: {
    name: 'requester_name',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Requester Name',
    label: 'Who is completing this request?',
    placeholder: 'Who is completing this request?',
    type: 'text',
    helpText: '',
    required: true,
  },
  requester_name_other: {
    name: 'requester_name_other',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Other Requester Name',
    label: 'Name of person completing this request?',
    placeholder: 'Name of person completing this request?',
    helpText: 'Only the person listed on the vehicle registration or an authorized individual may make changes to this policy.',
    type: 'text',
    required: true,
  },
  policy_number: {
    name: 'policy_number',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Policy Number',
    label: 'Which policy will this change take place on?',
    placeholder: 'Which policy will this change take place on?',
    helpText: '',
    type: 'text',
    required: true,
  },
  // address block
  postal_code: {
    name: 'postal_code',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Postal Code',
    label: 'Postal Code',
    placeholder: 'Postal Code',
    helpText: '',
    type: 'text',
    required: true,
  },
  new_unit_number: {
    name: 'new_unit_number',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Unit Number',
    label: 'Unit Number',
    placeholder: 'Unit Number',
    helpText: 'No unit number? Just leave the field blank.',
    type: 'text',
    required: false,
  },
  new_street_number: {
    name: 'new_street_number',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Street Number',
    label: 'Street Number',
    placeholder: 'Street Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  new_street_name: {
    name: 'new_street_name',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Street Name',
    label: 'Street Name',
    placeholder: 'Street Name',
    helpText: 'If your street isn\'t listed let us know. Start a web chat or give us a call at 1-888-881-8045.',
    type: 'text',
    required: true,
  },
  new_municipality: {
    name: 'new_municipality',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'City',
    label: 'City',
    placeholder: 'City',
    helpText: '',
    type: 'text',
    required: true,
  },
  new_province: {
    name: 'new_province',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Province',
    label: 'Province',
    placeholder: 'Province',
    helpText: '',
    type: 'text',
    required: true,
  },
  new_phone_number: {
    name: 'new_phone_number',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Phone Number',
    label: 'Phone Number',
    placeholder: 'Phone Number',
    helpText: 'Leave this field blank if there are no changes to your phone number.',
    type: 'text',
    required: false,
  },
  move_in_date: {
    name: 'move_in_date',
    formValueCategory: 'yourNewAddress',
    prettified_name: 'Moving Date',
    label: 'When do you move to your new address?',
    placeholder: 'When do you move to your new address?',
    helpText: 'If you\'ve already moved, please contact us. Start a web chat or call 1-888-881-8045.',
    type: 'text',
    required: true,
  },
  // VehicleInformationFields
  vin: {
    name: 'vin',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Vehicle Identification Number',
    label: 'VIN',
    placeholder: 'VIN',
    helpText: '',
    type: 'text',
    required: true,
  },
  vehicle_usage: {
    name: 'vehicle_usage',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Primary Usage',
    label: 'Primary Use',
    placeholder: 'Primary Use',
    helpText: 'Pleasure means your vehicle is used for leisure driving only. Commuting means your vehicle is used to drive to and from work and/or school, as well as for leisure driving. Business means your vehicle is used for work-related purposes and for leisure driving on occasion. For example, a sales person who uses their vehicle to meet with clients.',
    type: 'text',
    required: true,
  },
  vehicle_daily_kms: {
    name: 'vehicle_daily_kms',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Daily KM',
    label: 'Daily KM',
    placeholder: 'Daily KM',
    helpText: 'The approximate number of kilometres you drive one way to work/school daily.',
    endLabel: 'km',
    type: 'number',
    required: true,
  },
  vehicle_annual_kms: {
    name: 'vehicle_annual_kms',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Annual KM',
    label: 'Annual KM',
    placeholder: 'Annual KM',
    helpText: 'The total number of kilometres you drive annually for all uses.',
    type: 'number',
    endLabel: 'km',
    required: true,
  },
  business_vehicle_annual_kms: {
    name: 'business_vehicle_annual_kms',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Annual Business KM',
    label: 'Annual Business KM',
    placeholder: '',
    helpText: 'Please choose the number closest to the approximate number of kilometers that you drive for business purposes each year.',
    type: 'number',
    endLabel: 'km',
    required: true,
  },
  parked_at_night: {
    name: 'parked_at_night',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Parking Location',
    label: 'Where is the vehicle parked at night?',
    placeholder: 'Where is the vehicle parked at night?',
    helpText: '',
    type: 'text',
    required: true,
  },
  // Driver Information
  principle_driver: {
    name: 'principle_driver',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Principal Driver',
    label: 'Who will be the principal driver of the vehicle?',
    placeholder: 'Who will be the principal driver of the vehicle?',
    helpText: 'The person that drives the vehicle most, usually for commuting purposes.',
    type: 'text',
    required: true,
  },
  other_principle_driver_name: {
    name: 'other_principle_driver_name',
    formValueCategory: 'Other',
    prettified_name: 'Principal Driver',
    label: 'Driver\'s Name?',
    placeholder: 'Driver\'s Name?',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_principle_driver_licence: {
    name: 'other_principle_driver_licence',
    formValueCategory: 'Other',
    prettified_name: 'Principle Driver\'s Licence Number',
    label: 'Driver\'s Licence Number',
    placeholder: 'Driver\'s Licence Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver: {
    name: 'other_frequent_driver',
    formValueCategory: 'Other',
    prettified_name: 'Other Drivers',
    label: 'Are there any other licenced drivers in the household who are not listed on your policy?',
    placeholder: 'Are there any other licenced drivers in the household who are not listed on your policy?',
    helpText: 'If other drivers have access to your car, they may need to be on your policy as a secondary driver.',
    type: 'text',
    required: true,
  },
  other_frequent_driver_name: {
    name: 'other_frequent_driver_name',
    formValueCategory: 'Other',
    prettified_name: 'Driver Name',
    label: "Driver's Name",
    placeholder: 'Name',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_licence: {
    name: 'other_frequent_driver_licence',
    formValueCategory: 'Other',
    prettified_name: 'Driver Licence Number',
    label: "Driver's Licence Number",
    placeholder: 'Licence Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_name_1: {
    name: 'other_frequent_driver_name',
    formValueCategory: 'Other',
    prettified_name: 'Driver (1) Name',
    label: 'Driver\'s Name',
    placeholder: 'Name',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_licence_1: {
    name: 'other_frequent_driver_licence',
    formValueCategory: 'Other',
    prettified_name: 'Driver (1) Licence',
    label: 'Driver\'s Licence Number',
    placeholder: 'Licence Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_name_2: {
    name: 'other_frequent_driver_name',
    formValueCategory: 'Other',
    prettified_name: 'Driver (2) Name',
    label: 'Driver\'s Name',
    placeholder: 'Name',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_licence_2: {
    name: 'other_frequent_driver_licence',
    formValueCategory: 'Other',
    prettified_name: 'Driver (2) Licence',
    label: 'Driver\'s Licence Number',
    placeholder: 'Licence Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_name_3: {
    name: 'other_frequent_driver_name',
    formValueCategory: 'Other',
    prettified_name: 'Driver (3) Name',
    label: 'Driver\'s Name',
    placeholder: 'Name',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_licence_3: {
    name: 'other_frequent_driver_licence',
    formValueCategory: 'Other',
    prettified_name: 'Driver (3) Licence',
    label: 'Driver\'s Licence Number',
    placeholder: 'Licence Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_name_4: {
    name: 'other_frequent_driver_name',
    formValueCategory: 'Other',
    prettified_name: 'Driver (4) Name',
    label: 'Driver\'s Name',
    placeholder: 'Name',
    helpText: '',
    type: 'text',
    required: true,
  },
  other_frequent_driver_licence_4: {
    name: 'other_frequent_driver_licence',
    formValueCategory: 'Other',
    prettified_name: 'Driver (4) Licence',
    label: 'Driver\'s Licence Number',
    placeholder: 'Licence Number',
    helpText: '',
    type: 'text',
    required: true,
  },
  // coverage
  coverage_liability: {
    name: 'coverage_liability',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Liability',
    label: 'Liability',
    placeholder: 'Liability',
    helpText: 'Liability will provide coverage in the event if a third party were to bring a judgement against you.',
    type: 'text',
    required: true,
  },
  coverage_collision: {
    name: 'coverage_collision',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Collision',
    label: 'Collision',
    placeholder: 'Collision',
    helpText: 'Collision or Upset',
    type: '',
    required: true,
  },
  coverage_comprehensive: {
    name: 'coverage_comprehensive',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Comprehensive',
    label: 'Comprehensive',
    placeholder: 'Comprehensive',
    helpText: 'Comprehensive covers you for such things as fire, theft, vandalism, and glass breakage.',
    type: '',
    required: true,
  },
  endorsement_loss_of_use: {
    name: 'endorsement_loss_of_use',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Coverage for Transportation Replacement (20)',
    label: 'Coverage for Transportation Replacement (20)',
    placeholder: 'Coverage for Transportation Replacement (20)',
    helpText: 'If your vehicle is in the shop due to an insured claim, you can be reimbursed up to your limit for a rental car, taxi cab, or whatever you need to get around.',
    type: '',
    required: false,
  },
  endorsement_non_owned_autos: {
    name: 'endorsement_non_owned_autos',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Liability for Damage to Non-Owned Autos (27)',
    label: 'Liability for Damage to Non-Owned Autos (27)',
    placeholder: 'Liability for Damage to Non-Owned Autos (27)',
    helpText: 'If you happen to rent a vehicle anywhere in Canada or the U.S., you do not need to purchase coverage for that rental vehicle, this policy covers any damage up to your limit.',
    type: '',
    required: false,
  },
  endorsement_depreciation: {
    name: 'endorsement_depreciation',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Limited Waiver of Depreciation/Limited Waiver of Depreciation for Specified Lessee(s)',
    label: 'Limited Waiver of Depreciation/Limited Waiver of Depreciation for Specified Lessee(s)',
    placeholder: 'Limited Waiver of Depreciation/Limited Waiver of Depreciation for Specified Lessee(s)',
    helpText: 'In case you ever get into an accident which causes the full loss of your vehicle within the first few months you own it, you will be reimbursed for the purchase price, not the depreciated value of the vehicle.',
    type: 'checkbox',
    required: false,
  },
  endorsement_accident: {
    name: 'endorsement_accident',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Accident Waiver',
    label: 'Accident Waiver',
    placeholder: 'Accident Waiver',
    helpText: 'In the event of you being in an accident in which you are at fault, it will protect your driving record and forgive the accident.',
    type: 'checkbox',
    required: false,
  },
  endorsement_conviction: {
    name: 'endorsement_conviction',
    formValueCategory: 'YMMVIN',
    prettified_name: 'Conviction Protector',
    label: 'Conviction Protector',
    placeholder: 'Conviction Protector',
    helpText: 'In the event of your first Minor Conviction, this endorsement will prevent you from losing your Conviction Free discount. ',
    type: 'checkbox',
    required: false,
  },
};

export default schema;
