// @flow
export const constants = ((): ConstantsType => {
  const ROOT_URL: string = 'http://localhost:8000';

  return {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',

    AUTHENTICATING: 'AUTHENTICATING',
    AUTHENTICATED: 'AUTHENTICATED',
    REDUX_STATE_CLEAR: 'REDUX_STATE_CLEAR',

    VERIFY_TOKEN: 'VERIFY_TOKEN',

    // Goals
    GOAL_CREATE_REQUEST: 'GOAL_CREATE_REQUEST',
    GOALS_FETCH_REQUEST: 'GOALS_FETCH_REQUEST',
    GOAL_EDIT_REQUEST: 'GOAL_EDIT_REQUEST',
    GOAL_DELETE_REQUEST: 'GOAL_DELETE_REQUEST',
    GOAL_CREATING: 'GOAL_CREATING',
    GOAL_CREATED: 'GOAL_CREATED',
    GOALS_FETCHING: 'GOALS_FETCHING',
    GOALS_FETCHED: 'GOALS_FETCHED',
    GOAL_EDITED: 'GOAL_EDITED',
    GOAL_DELETED: 'GOAL_DELETED',

    // Users
    USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
    USER_FETCH_REQUEST: 'USER_FETCH_REQUEST',
    USER_EDIT_REQUEST: 'USER_EDIT_REQUEST',
    USER_CREATING: 'USER_CREATING',
    USER_CREATED: 'USER_CREATED',
    USER_FETCHING: 'USER_FETCHING',
    USER_FETCHED: 'USER_FETCHED',
    USER_EDITED: 'USER_EDITED',

    // URLs
    ROOT_URL: ROOT_URL,
    GOALS_URL: `${ROOT_URL}/goals/`,
    USERS_URL: `${ROOT_URL}/users/`,
    TOKEN_OBTAIN_URL: `${ROOT_URL}/token/`,
    TOKEN_VERIFY_URL: `${ROOT_URL}/verify/`,
  };
})();

type ConstantsType = {
  LOGIN_REQUEST: string,
  LOGOUT_REQUEST: string,
  SIGNUP_REQUEST: string,

  AUTHENTICATING: string,
  AUTHENTICATED: string,
  REDUX_STATE_CLEAR: string,

  VERIFY_TOKEN: string,

  // Goals
  GOAL_CREATE_REQUEST: string,
  GOALS_FETCH_REQUEST: string,
  GOAL_EDIT_REQUEST: string,
  GOAL_DELETE_REQUEST: string,
  GOAL_CREATING: string,
  GOAL_CREATED: string,
  GOALS_FETCHING: string,
  GOALS_FETCHED: string,
  GOAL_EDITED: string,
  GOAL_DELETED: string,

  // Users
  USER_CREATE_REQUEST: string,
  USER_FETCH_REQUEST: string,
  USER_EDIT_REQUEST: string,
  USER_CREATING: string,
  USER_CREATED: string,
  USER_FETCHING: string,
  USER_FETCHED: string,
  USER_EDITED: string,

  // URLs
  ROOT_URL: string,
  GOALS_URL: string,
  USERS_URL: string,
  TOKEN_OBTAIN_URL: string,
  TOKEN_VERIFY_URL: string,
}

export default constants;
