# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='Todo', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
