export const constants = ((environment = 'local') => {
  let ROOT_URL;
  switch (environment) {
    case 'local':
      ROOT_URL = 'http://localhost:8000';
      break;
    default:
      ROOT_URL = 'http://localhost:8000';
  }

  return {
    // Decks
    DECK_CREATE_REQUEST: 'DECK_CREATE_REQUEST',
    DECKS_FETCH_REQUEST: 'DECKS_FETCH_REQUEST',
    DECK_EDIT_REQUEST: 'DECK_EDIT_REQUEST',
    DECK_DELETE_REQUEST: 'DECK_DELETE_REQUEST',

    DECK_CREATING: 'DECK_CREATING',
    DECK_CREATED: 'DECK_CREATED',
    DECKS_FETCHING: 'DECKS_FETCHING',
    DECKS_FETCHED: 'DECKS_FETCHED',
    DECK_EDITED: 'DECK_EDITED',
    DECK_DELETED: 'DECK_DELETED',

    // Hands
    HAND_CREATE_REQUEST: 'HAND_CREATE_REQUEST',
    HANDS_FETCH_REQUEST: 'HANDS_FETCH_REQUEST',
    HAND_EDIT_REQUEST: 'HAND_EDIT_REQUEST',
    HAND_DELETE_REQUEST: 'HAND_DELETE_REQUEST',

    HAND_CREATING: 'HAND_CREATING',
    HAND_CREATED: 'HAND_CREATED',
    HANDS_FETCHING: 'HANDS_FETCHING',
    HANDS_FETCHED: 'HANDS_FETCHED',
    HAND_EDITED: 'HAND_EDITED',
    HAND_DELETED: 'HAND_DELETED',

    // Cards
    CARD_CREATE_REQUEST: 'CARD_CREATE_REQUEST',
    CARDS_FETCH_REQUEST: 'CARDS_FETCH_REQUEST',
    CARD_EDIT_REQUEST: 'CARD_EDIT_REQUEST',
    CARD_DELETE_REQUEST: 'CARD_DELETE_REQUEST',

    CARD_CREATING: 'CARD_CREATING',
    CARD_CREATED: 'CARD_CREATED',
    CARDS_FETCHING: 'CARDS_FETCHING',
    CARDS_FETCHED: 'CARDS_FETCHED',
    CARD_EDITED: 'CARD_EDITED',
    CARD_DELETED: 'CARD_DELETED',

    // MiniCards
    MINICARD_CREATE_REQUEST: 'MINICARD_CREATE_REQUEST',
    MINICARDS_FETCH_REQUEST: 'MINICARDS_FETCH_REQUEST',
    MINICARD_EDIT_REQUEST: 'MINICARD_EDIT_REQUEST',
    MINICARD_DELETE_REQUEST: 'MINICARD_DELETE_REQUEST',

    MINICARD_CREATING: 'MINICARD_CREATING',
    MINICARD_CREATED: 'MINICARD_CREATED',
    MINICARDS_FETCHING: 'MINICARDS_FETCHING',
    MINICARDS_FETCHED: 'MINICARDS_FETCHED',
    MINICARD_EDITED: 'MINICARD_EDITED',
    MINICARD_DELETED: 'MINICARD_DELETED',

    // Comments
    COMMENT_CREATE_REQUEST: 'COMMENT_CREATE_REQUEST',
    COMMENTS_FETCH_REQUEST: 'COMMENTS_FETCH_REQUEST',
    COMMENT_EDIT_REQUEST: 'COMMENT_EDIT_REQUEST',
    COMMENT_DELETE_REQUEST: 'COMMENT_DELETE_REQUEST',

    COMMENT_CREATING: 'COMMENT_CREATING',
    COMMENT_CREATED: 'COMMENT_CREATED',
    COMMENTS_FETCHING: 'COMMENTS_FETCHING',
    COMMENTS_FETCHED: 'COMMENTS_FETCHED',
    COMMENT_EDITED: 'COMMENT_EDITED',
    COMMENT_DELETED: 'COMMENT_DELETED',

    // Users
    USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
    USER_FETCH_REQUEST: 'USER_FETCH_REQUEST',
    USER_EDIT_REQUEST: 'USER_EDIT_REQUEST',
    USER_DELETED_REQUEST: 'USER_DELETED_REQUEST',

    USER_CREATING: 'USER_CREATING',
    USER_CREATED: 'USER_CREATED',
    USER_FETCHING: 'USER_FETCHING',
    USER_FETCHED: 'USER_FETCHED',
    USER_EDITED: 'USER_EDITED',
    USER_DELETED: 'USER_DELETED',

    // URLs
    ROOT_URL: ROOT_URL,
    GOALS_URL: `${ROOT_URL}/goals/`,
    USERS_URL: `${ROOT_URL}/users/`,
  };
})();

export default constants;
