# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='hightlighted',
            new_name='highlighted',
        ),
    ]
