# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_contentediter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentediter',
            name='picture',
            field=models.ImageField(blank=True, upload_to='meals'),
        ),
    ]
